import { Letter } from './letter';

export const ALPHABET: Letter[] = [
  { value: 'a', isFound: null },
  { value: 'b', isFound: null },
  { value: 'c', isFound: null },
  { value: 'd', isFound: null },
  { value: 'e', isFound: null },
  { value: 'f', isFound: null },
  { value: 'g', isFound: null },
  { value: 'h', isFound: null },
  { value: 'i', isFound: null },
  { value: 'j', isFound: null },
  { value: 'k', isFound: null },
  { value: 'l', isFound: null },
  { value: 'm', isFound: null },
  { value: 'n', isFound: null },
  { value: 'o', isFound: null },
  { value: 'p', isFound: null },
  { value: 'q', isFound: null },
  { value: 'r', isFound: null },
  { value: 's', isFound: null },
  { value: 't', isFound: null },
  { value: 'u', isFound: null },
  { value: 'v', isFound: null },
  { value: 'w', isFound: null },
  { value: 'x', isFound: null },
  { value: 'y', isFound: null },
  { value: 'z', isFound: null },
];

export const WORDS: string[] = [
  "potatoes",
  "banc",
  "ordinateur",
  "restaurant",
  "code",
  "elephant",
  "mouton",
  "croquettes",
  "mobile",
  "compilateur",
  "processus",
  "architecture",
  "cactus",
  "rhododendron",
  "disque",
  "acier"
]